### ISSUE TITLE
support multiple destination path 

### ISSUE THREAD

**Issue by prasoon-pxc** [xelalexv/dregsy#113]
I have an use-case where if I am copying any image to ecr on **"/production"** path it will get copied to different ecr accounts i.e staging and prod but **"/development"** is for dev ecr, Now I want to copy same image to all my ecr accounts  based on path based rules, so looking for option to define multiple "to" in list

Example: 
```
    - from: adamboutcher/statping-ng
      to: development/thirdparty/adamboutcher/statping
      to: production/thirdparty/adamboutcher/statping
      tags: ['v0.90.78']

```

**Comment by xelalexv** [comment]
It's somewhat repetitive, but if it's not too many paths you could do:

```
- from: adamboutcher/statping-ng
  to: development/thirdparty/adamboutcher/statping
  tags: &tags
  - 'v0.90.78'
- from: adamboutcher/statping-ng
  to: production/thirdparty/adamboutcher/statping
  tags: *tags
```
The use of YAML anchor & alias at least spares you repeating the tags list (see also issue #91). Haven't tried this out though.

**Comment by prasoon-pxc** [comment]
thanks @xelalexv , I think this YAML anchor is not that much useful here , because I will want to copy to multiple paths here

**Comment by prasoon-pxc** [comment]
I don't think so, because I am using helm chart template to define config file and defining multiple mapping entries will increase the complexity of chart.

Like this:

```
 {{- if .Values.quaytoecr.enabled }}    
     - name: quaytoecr
       verbose: true
       source:
         registry: quay.io
         skip-tls-verify: true
       target:
         registry: {{ .Values.targetparameters.targetregistry }}
         auth-refresh: 5h
         skip-tls-verify: true
       mappings:
           {{- toYaml .Values.quaytoecr.image_syncer_quaytoecr | nindent 8 }}  
```

Also, I think it is not possible to define like mapping like this?

```
- name: one
  source: &source
    registry: source.reg
  target:
    registry: foo
  mappings: &mappings
  - from: adamboutcher/statping-ng
    to: development/thirdparty/adamboutcher/statping
    tags: ['v0.90.78']


- name: two
  source: *source
  target:
    registry: bar
  mappings: *mappings
  - to: production/thirdparty/adamboutcher/statping
```
