### ISSUE TITLE
Unable to sync insecure registries

### ISSUE THREAD

**Issue by tardich** [xelalexv/dregsy#26]
There should be an option to set registries as insecure registries, something like:

```
tasks:
  - name: task1
    source:
      registry: my_fancy_registry
      insecure: no
    target:
      registry: my_not_so_fancy_registry:5000
      insecure: yes
```

So the client would do http instead of https for the target registry in my example

**Comment by RaJiska** [comment]
This is already possible, however it is only supported on Skopeo relay as changing this option on Docker requires (at the current time) to edit the daemon configuration. To achieve this using Skopeo, add the `skip-tls-verify: true` option in your configuration file, as such:

```
relay: skopeo

skopeo:
  binary: skopeo
  certs-dir: /etc/skopeo/certs.d

tasks:
  - name: task1
    source:
      registry: my_fancy_registry
    target:
      registry: my_not_so_fancy_registry:5000
      skip-tls-verify: true
```
