### ISSUE TITLE
add support for a blacklist tag array

### ISSUE THREAD

**Issue by callum-tait-pbx** [xelalexv/dregsy#46]
Sometimes you want to sync everything BUT a set of tags, this would be a great addition and I would think fairly quick to implement for someone who knows Go, sadly this person isn't me :(

```yaml
    mappings:
      - from: repository/image
        to: repository/image
        blacklist-tags: ['some_tag', 'another_tag']
```
