### ISSUE TITLE
sync the whole registry 

### ISSUE THREAD

**Issue by karasjoh000** [xelalexv/dregsy#49]
Is there a way to sync the full registry? I tried `from: *` and `from: regex:*` but this errors happen: 
```bash 
time="2021-04-07T23:20:18Z" level=info msg=mapping from="/*" to="/*"                                     
time="2021-04-07T23:20:18Z" level=error msg="error listing image tags for ref 'source/*': time=\"2021-04-07T23:20:18Z\" level=fatal msg=\"invalid reference format\"\n, exit status 1"                                                                                                  
time="2021-04-07T23:20:18Z" level=error msg="one or more tasks had errors, please see log for details"
```
```bash 
time="2021-04-07T23:31:43Z" level=info msg=mapping from="/regex:*" to="/regex:*"                         
time="2021-04-07T23:31:43Z" level=error msg="error listing image tags for ref 'source/regex:*': time=\"2021-04-07T23:31:43Z\" level=fatal msg=\"invalid reference format\"\n,exit status 1"
```

```yaml
relay: skopeo
tasks:
  - name: sync # required
    verbose: true
    source:
      registry: source
      skip-tls-verify: true
    target:
      registry: target
      skip-tls-verify: true
    mappings:
      - from: "*"
```
