### ISSUE TITLE
invalid character '_' looking for beginning of value

### ISSUE THREAD

**Issue by mkhodave** [xelalexv/dregsy#50]
I am trying to dregsy image & skopeo relay for copying dockerhub image to google artifact registry repository but seeing following error

`time="2021-04-15T07:54:53Z" level=error msg="invalid character '_' looking for beginning of value"`

following is config.yaml file 

```
relay: skopeo

# relay config sections
skopeo:
  binary: skopeo
  certs-dir: /etc/skopeo/certs.d

# list of sync tasks
tasks:

  - name: task1 # required
    interval: 60
    verbose: true
    source:
      registry: registry.hub.docker.com
      auth: <dockerhub_auth>
      lister:
        type: dockerhub
    target:
      registry: <google_artifact_registry_URL>
      auth: none
      skip-tls-verify: false
    mappings:
      - from: regex:xelalex/dregsy.*
        to: test/upstream/dregsy
        tags: ['master', 'latest']
```
Any help much appreciated
