### ISSUE TITLE
AWS ECR example in documentation

### ISSUE THREAD

**Issue by kivio** [xelalexv/dregsy#6]
Will be good in AWS ECR example to describe whole process how it should look, like:
- how dregsy config should look
- what additional commands i must do like aws login or something (or is dregsy doing it for me)
- what more?

**Comment by kivio** [comment]
Another question - is possible to use ECR as source or just as target - i have problem with find that code here.

**Comment by kivio** [comment]
@xelalexv - will be possible to make some debugging session with you?

**Comment by xelalexv** [comment]
_ECR_ repos can be used in sources and targets. In most cases, all you need to do is to specify `auth-refresh` with a time interval, e.g. `auth-refresh: 6h`, instead of setting `auth`. _dregsy_ will then take care of authenticating with _ECR_. A prerequisite however is that you either set access key ID and secret access key in _dregsy_'s environment, or if you're running _dregsy_ on an _EC2_ instance inside the used _AWS_ account, attach an according instance profile to this instance. Details are explained in the _AWS ECR_ section of the readme. Let me know where the doc could be improved or is not clear enough.

**Comment by kivio** [comment]
I have configuration like that:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name:  aws-creds
stringData:
  aws.access_key: AxxQ
  aws.secret: Qxxx3
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dregsy-config
data:
  config.yaml: |-
    relay: skopeo
    tasks:
      - name: synchro
        interval: 60
        source:
          registry: xyz.dkr.ecr.eu-west-1.amazonaws.com
          auto-refresh: 10h
        target:
          registry: xyz-registry-svc.xyz.svc
          skip-tls-verify: true
        mappings:
         - from: rabbitmq

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dregsy-updater
  labels:
    k8s-app: dregsy-updater
    kubernetes.io/cluster-service: "true"
spec:
  serviceName: dregsy-updater
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: dregsy-updater
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: dregsy
        image: xelalex/dregsy
        command: ['/dregsy', '-config=/config/config.yaml']
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: aws.access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: aws.secret
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
        volumeMounts:
        - name: dregsy-config
          mountPath: /config
      volumes:
      - name: dregsy-config
        configMap:
          name: dregsy-config
          items:
          - key: config.yaml
            path: config.yaml
```

Also try these credentials in console and i can do everything with ECR registry using it. I have policy set to ECRPowerUser. 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:DescribeRepositories",
                "ecr:ListImages",
                "ecr:DescribeImages",
                "ecr:BatchGetImage",
                "ecr:InitiateLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:CompleteLayerUpload",
                "ecr:PutImage"
            ],
            "Resource": "*"
        }
    ]
}
```

But logs continously looks like:
```log

2019-04-08T12:48:36Z [INFO]
--
  | 2019-04-08T12:48:36Z [INFO] skopeo version 0.1.32
  | 2019-04-08T12:48:36Z [INFO] skopeo relay ready
  | 2019-04-08T12:48:36Z [INFO] waiting for next sync task...
  | 2019-04-08T12:48:36Z [INFO]
  | 2019-04-08T12:48:36Z [INFO] syncing task 'synchro': 'xyz.dkr.ecr.eu-west-1.amazonaws.com' --> 'xyz-registry-svc.xyz.svc'
  | 2019-04-08T12:48:36Z [INFO] mapping '/rabbitmq' to '/rabbitmq'
  | 2019-04-08T12:48:36Z [INFO]
  | 2019-04-08T12:48:36Z [INFO] waiting for next sync task...
  | 2019-04-08T12:48:36Z [INFO]
  | 2019-04-08T12:48:36Z [ERROR] error listing image tags: time="2019-04-08T12:48:36Z" level=fatal msg="Error reading manifest latest in xyz.dkr.ecr.eu-west-1.amazonaws.com/rabbitmq: unauthorized: authentication required"
  | , exit status 1
  | 2019-04-08T12:49:36Z [INFO] syncing task 'synchro': 'xyz.dkr.ecr.eu-west-1.amazonaws.com' --> 'xyz-registry-svc.xyz.svc'
  | 2019-04-08T12:49:36Z [INFO] mapping '/rabbitmq' to '/rabbitmq'
  | 2019-04-08T12:49:36Z [ERROR] error listing image tags: time="2019-04-08T12:49:36Z" level=fatal msg="Error reading manifest latest in xyz.dkr.ecr.eu-west-1.amazonaws.com/rabbitmq: unauthorized: authentication required"
  | , exit status 1


```
