### ISSUE TITLE
Repo name duplication when using wildcards

### ISSUE THREAD

**Issue by sjthespian** [xelalexv/dregsy#66]
I am seeing some very odd duplication of repo names now that I have wildcards working (I moved to using eco.io as my source repo). For example with the config below, I see it trying to do this sync:
```
time="2022-02-08T17:45:04Z" level=info msg=mapping from="regex:myrepo/.*" to="regex:myrepo/(.+),$1/"
time="2022-02-08T17:45:04Z" level=info msg="refreshing credentials" registry=123456789.dkr.ecr.us-east-1.amazonaws.com
time="2022-02-08T17:45:07Z" level=info msg="refreshing credentials" registry="registry1.example.com:8083"
time="2022-02-08T17:45:07Z" level=debug msg="retrieving repository list"
time="2022-02-08T17:45:07Z" level=debug msg="ECR retrieving image list"
time="2022-02-08T17:45:10Z" level=debug msg="caching repository list"
time="2022-02-08T17:45:10Z" level=info msg="syncing tag" tag=5.0.6-alpine
time="2022-02-08T17:45:10Z" level=debug msg="time=\"2022-02-08T17:45:10Z\" level=info msg=\"Tag presence check\" imagename=\"123456789.dkr.ecr.us-east-1.amazonaws.com/myrepo/baserepo/redis:5.0.6-alpine\" tagged=true"
time="2022-02-08T17:45:10Z" level=debug msg="time=\"2022-02-08T17:45:10Z\" level=info msg=\"Copying image ref 1/1\" from=\"docker://123456789.dkr.ecr.us-east-1.amazonaws.com/myrepo/baserepo/redis:5.0.6-alpine\" to=\"docker://registry1.example.com:8083/baserepo/redis/redis:5.0.6-alpine\""
```
notice the redis/redis on the last line. I would expect that to just be `baserepo/redis:5.0.6-alpine`.

My config:
```
docker:
  api-version: '1.24'
  dockerhost: unix:///var/run/docker.sock
lister:
  cacheDuration: 1h
  maxItems: 100
relay: skopeo
skopeo:
  binary: skopeo
  mode: sync
tasks:
  - name: sync-reg1
    interval: 1800
    source:
      registry: 123456789.dkr.ecr.us-east-1.amazonaws.com
      auth-refresh: 1h
    target:
      registry: registry1.example.com:8083
    mappings:
    - from: regex:myrepo/.*
      to: regex:myrepo/(.+),$1/
    verbose: true
```

I have tried the `to:` regex with and without the trailing slash, it doesn't seem to make a difference. From the docs, and my earlier testing when I wasn't using a regex for the `from:` config, I would think this should work. I'm going try try something crazy like this next `to: regex:myrepo/(.+)/[^/]*$,$1`. But I'm afraid that will end up syncing `/baserepo:5.0.6-alpine` in the example above.

Any ideas why it's doubling the repo name?
