### ISSUE TITLE
[feat req/debate] adding support for image digests with the skopeo relay

### ISSUE THREAD

**Issue by nicop311** [xelalexv/dregsy#86]
Hello @all, I am currently trying to figure out how to add support for **image digests** copy/sync in `dregsy`.

I think this is even simpler to implement than the tags based mapping which supports using regular expression to search through tags. Indeed with image digests, there is no need for search with regular expression, since a digest is unique and uniquely identify one particular image.

Image digest are also more robust than tags in certain situation when there is the need to match a very precise version of an image. And image digest are also used for crypto signature of container images.

What do you think about that? I must say, the `dregsy` source code is not really well documented. But I think I am starting to understand it a bit. I have several ideas as well.

## Description of image digests

An image digest looks like this below: using [`crane`](https://github.com/google/go-containerregistry/blob/main/cmd/crane)

```
$ crane digest --platform="linux/amd64" library/busybox:1.29.2
```
```
sha256:5e8e0509e829bb8f990249135a36e81a3ecbe94294e7a185cc14616e5fad96bd
```

## `skopeo` & digests

A `skopeo copy` command using digest rather than tags looks like this :

```bash
skopeo copy --preserve-digests docker://docker.io/registry@sha256:cc6393207bf9d3e032c4d9277834c1695117532c9f7e8c64e7b7adcda3a85f39      docker-archive:./registry-linux-amd64-2.8.1.tar:myreg.net/mypath/registry:2.8.1
```

**Important note:** Skopeo (1.10.0) DOES NOT support using tags and digest at the same time.

## dregsy configuration with digests

Below is an example of what could be a `dregsy-config.yaml` file which uses digests

```yaml
# test/fixtures/config/skopeo-digest-valid.yaml
relay: skopeo

lister:
  maxItems: 50
  cacheDuration: 30m

tasks:
- name: test-skopeo-digest-valid
  interval: 30
  verbose: true
  source:
    registry: registry.hub.docker.com
  target:
    registry: 127.0.0.1:5000
    auth: something
    skip-tls-verify: true
  mappings:
  # Tags based mapping
  #~~~~~~~~~~~~~~~~~
  - from: library/busybox
    to: skopeo/library/busybox
    tags: ['1.29.2', '1.29.3', 'latest']
    platform: linux/arm/v6

  # Digests based mapping
  #~~~~~~~~~~~~~~~~~~~~
  - from: library/busybox
    digests:
    - sha256:5e8e0509e829bb8f990249135a36e81a3ecbe94294e7a185cc14616e5fad96bd
    - sha256:76582bc9c59276ea11459bf5ff4f54fd5b7fd23ff622d80479156108fdd26470
    - sha256:6ba3c395f0a2941114d8dcdf80bedcc7e654252f5870dd94daff9cc3188f3eb2
    to: skopeo/library/busybox

  # Using either the WEB GUI at https://hub.docker.com/_/busybox/tags. Or using
  # the tool crane* to get digests from CLI.
  # *crane : https://github.com/google/go-containerregistry/tree/main/cmd/crane
  #
  # $ crane digest --platform="linux/amd64" library/busybox:1.29.2
  # sha256:5e8e0509e829bb8f990249135a36e81a3ecbe94294e7a185cc14616e5fad96bd
  #
  # $ crane digest --platform="linux/arm/v6" library/busybox:1.29.2
  # sha256:6ba3c395f0a2941114d8dcdf80bedcc7e654252f5870dd94daff9cc3188f3eb2
  #
  # $ crane digest --platform="linux/arm64" library/busybox:1.29.3
  # sha256:76582bc9c59276ea11459bf5ff4f54fd5b7fd23ff622d80479156108fdd26470
```

It is probably better to differentiate and separate "Tags based mapping" and "Digests based mapping", since `skopeo` does not support both at the same time.

However it might be possible to have a more compact version where both a tag list and a digest list are part of the same mapping object. The `skopeo copy` requests are different when they use tags or digest (see above the skopeo example with digest).

Also with digest, you can ignore `platform:`, since the digest already uniquely identify a precise image.

```yaml
  mappings:
  # Tags based mapping
  #~~~~~~~~~~~~~~~~~
  - from: library/busybox
    to: skopeo/library/busybox
    tags: ['1.29.2', '1.29.3', 'latest']
    platform: linux/arm/v6
    digests:
    - sha256:5e8e0509e829bb8f990249135a36e81a3ecbe94294e7a185cc14616e5fad96bd
    - sha256:76582bc9c59276ea11459bf5ff4f54fd5b7fd23ff622d80479156108fdd26470
    - sha256:6ba3c395f0a2941114d8dcdf80bedcc7e654252f5870dd94daff9cc3188f3eb2
```

But it might be overkill to dedicate `task` to either tag only or digest only.

**Comment by xelalexv** [comment]
> I am currently trying to figure out how to add support for **image digests** copy/sync in `dregsy`.

That's an interesting feature that would nicely complement the current functionality.

> Indeed with image digests, there is no need for search with regular expression, since a digest is unique and uniquely identify one particular image ...
> ... It is probably better to differentiate and separate "Tags based mapping" and "Digests based mapping", since `skopeo` does not support both at the same time.

Keeping the two separate would actually be required. Syncing via digest and syncing via tag list, tag filtering & image matching address two fundamentally different uses cases. Syncing via digest is adequate when we know **exactly** what to sync beforehand, and that set does not change (at least not frequently). Tag filtering and image mapping however are indispensable when we do not know in advance what we need to sync, for example when we want to continuously sync various image streams produced by image build pipelines. For this we need to describe the set with rules, such as regular expressions or semver filters, and cannot use digests.

**Comment by nicop311** [comment]
@xelalexv awesome, thank you for your comment.
I have a prototype (on a private repo), which is working relatively good. I am currently creating a public fork, from which I will do a PR.

The behavior of my `dregsy` fork with support for digests sync is as follow. It does not change the behavior with tags (and all your filters).

***

## 0.4.4 dregsy behavior (current)

If the tags field is completely empty in the `dregsy` configuration file,
this gets all the existing tags on the source registry for a given image.

If the tags field is NOT empty, several filters (regex, semver, etc...) are used to get only the tags matching the filters.

## New feature: add support for digest in dregsy (my fork)

I propose 2 new fields in `mappings:`:

* `digests:` a list of digests
* `preserve-digests:` a `skopeo copy` command parameter

```yaml
[...]
  mappings:
  - from: library/busybox
    to: skopeo/library/busybox
    digests:
    - sha256:5e8e0509e829bb8f990249135a36e81a3ecbe94294e7a185cc14616e5fad96bd
    - sha256:76582bc9c59276ea11459bf5ff4f54fd5b7fd23ff622d80479156108fdd26470
    - sha256:6ba3c395f0a2941114d8dcdf80bedcc7e654252f5870dd94daff9cc3188f3eb2
    preserve-digests: true
    tags: ['1.29.2', '1.29.3', 'latest']
    platform: linux/arm/v6
```


3 cases for the `sync()` method:
1. If `digests` list is empty AND `tags` is empty, then Expand tags.
   This is the same behavior than dregsy v0.4.4: copy all available tags.
2. If `digestList` is not empty AND `tagsList` is not empty, then Expand tags and get digests.
   Both expand tags & pull the images corresponding the list of digests.
3. If `digestList` is not empty AND `tagsList` is empty, then do not Expand tags ; only pull the images corresponding the list of digests.


I also implemented various tests on the digest to **detect and ignore wrong digests**. Wrong digests are digests that do not exist or that are not correctly formated. This ensure that `dregsy` will run smoothly, even if digests are incorrect.

**Comment by xelalexv** [comment]
My thoughts about the implementation of this feature in PR #95:

I think we do not need to add the extra `digests` list to mappings, but can rather handle digests simply within the `tags` list. When a tag is verbatim, i.e. not a tag filter expression (`regex:` or `semver:`), we can parse it and check for the presence of a digest. With a minimal change to the Skopeo relay, a mapping such as this one already works:

```YAML
mappings:
- from: library/busybox
  to: base-skopeo/digest/busybox
  tags:
  - sha256:acaddd9ed544f7baf3373064064a51250b14cfe3ec604d65765a53da5958e5f5
```

This will reduce the change set quite a bit. It would be mostly confined to the relays (it should be possible to offer this for the Docker relay as well), and the tag set. In tag set, we need to consider whether a tag is/contains a digest during tag pruning, since digests should never be pruned.
