### ISSUE TITLE
platform architecture destination tag labeling 

### ISSUE THREAD

**Issue by pwu-nia** [xelalexv/dregsy#88]
hi, i was wondering if dregsy has the ability to label the destination tag based on different architecture, so for instance tag (v4.7, amd64), (v4.6,aarch) when specifying platform: all in the config.yaml. 

Thanks.

**Comment by xelalexv** [comment]
A tag on a multi-platform image defines a list of manifests, each pointing to an image for a particular platform for that tag. For example, try:

```
docker manifest inspect --verbose library/busybox:1.36
```

Creating a tag on a multi-platform image for only one particular platform is to my knowledge not possible. If there is a way, let me know.

If you want to separate out the different platform specific images from a multi-platform image, you could use separate mappings, for example:

```yaml
  mappings:
  - from: library/busybox
    to: library/busybox-arm64
    tags: ['latest']
    platform: linux/arm64/v8
  - from: library/busybox
    to: library/busybox-amd64
    tags: ['latest']
    platform: linux/amd64
```

It could be interesting to add something like `platform: all-split`, which would act as if mappings such as above had been defined for all available platforms. A sync using this would then automatically include new platforms as they are added in the source.
