### ISSUE TITLE
1 to many target mapping?

### ISSUE THREAD

**Issue by pwu-nia** [xelalexv/dregsy#91]
hey @xelalexv do we have support 1 source to many target image syncing per task? duplicating two tasks per each image mapping i believe would be more efficient for a long list of images.

**Comment by xelalexv** [comment]
This is not currently supported. However, you can use YAML anchors & aliases to avoid the duplications. For example:

```YAML
tasks:

- name: one
  source: &source
    registry: source.reg
  target:
    registry: foo
  mappings: &mappings
  - from: library/busybox
    to: base/library/busybox
    tags: ['a', 'b', 'c']
  - ...

- name: two
  source: *source
  target:
    registry: bar
  mappings: *mappings
```
An advantage would be that you could sync different targets at different intervals, if that's desired.
